[package]
name = "test_tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zksync_crypto = { path = "../../lib/crypto", version = "1.0" }
rand = "0.8"
serde = "1.0"
serde_json = "1.0"
csv = "1.1"

[dev-dependencies]
zksync_crypto = { path = "../../lib/crypto", version = "1.0" }
criterion = "0.3.0"
